;/*FB_PKG_DELIM*/

__d("FDSFollowFilled20Icon",["cr:14952"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14952")}),98);
__d("FDSFollowFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("618353"),20),u=e;l.default=u}),98);
__d("FDSUnfollowFilled20Icon",["cr:15846"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:15846")}),98);
__d("FDSUnfollowFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("578903"),20),u=e;l.default=u}),98);
__d("useGHLScrambledLabelMitigationLogger",["CometGHLFeedFallbackContext","CometGHLScrambledLabelMitigationLoggerContext","GHLMitigationsGating","GhlMitigationFalcoEvent","react","react-compiler-runtime"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.useContext,c=s.useEffect,d=s.useRef;function m(e){var t=o("react-compiler-runtime").c(6),n=u(r("CometGHLFeedFallbackContext")),a=n.isFallbackEnabled,i;t[0]===Symbol.for("react.memo_cache_sentinel")?(i=o("GHLMitigationsGating").getIsGHLFallbackToScramblerEnabled(),t[0]=i):i=t[0];var l=i,s=d(!1),m=u(r("CometGHLScrambledLabelMitigationLoggerContext")),p=m.trackingData,_,f;t[1]!==a||t[2]!==e||t[3]!==p?(_=function(){e===null||!o("GHLMitigationsGating").getIsGHLScrambledLabelMitigationLoggerEnabled()||s.current===!0||a&&l||(r("GhlMitigationFalcoEvent").log(function(){return{mitigation:e,xt:p}}),s.current=!0)},f=[a,l,e,p],t[1]=a,t[2]=e,t[3]=p,t[4]=_,t[5]=f):(_=t[4],f=t[5]),c(_,f)}l.default=m}),98);
__d("GHLRandomElementWrapperNotSSRSafe",["Random","react","react-compiler-runtime","stylex","useGHLScrambledLabelMitigationLogger"],(function(t,n,r,o,a,i,l){"use strict";var e,s,u=s||(s=o("react")),c={noop:{boxSizing:"x9f619",display:"xt0psk2",fontFamily:"xjb2p0i",fontSize:"x1qlqyl8",lineHeight:"x15bjb6t",$$css:!0}},d=[[1,0],[1,1],[0,1],[0,2],[1,2],[2,2],[2,1],[1,1]],m=Math.floor(Date.now()/(1e3*60*60*24)),p=function(t){var e;return(e={},e[t]=(function(e){function t(){return e.apply(this,arguments)||this}return babelHelpers.inheritsLoose(t,e),t})(babelHelpers.wrapNativeSuper(HTMLSpanElement)),e)[t]},_=function(){return String.fromCharCode(97+r("Random").random()*25)},f=m%10+5,g=Array(f).fill().map(_).join(""),h=Array(f).fill().map(_).join(""),y=g+"-"+h;window.customElements&&window.customElements.define(y,p(g),{extends:"span"});function C(t){var n=o("react-compiler-runtime").c(8),a=t.children,i=t.elementTag,l=t.mitigationToLog,s=t.useClassStyles,p=t.useInlineStyles,_=s===void 0?!1:s,f=p===void 0?!1:p,g=a,h=d[m%d.length],C;n[0]!==f?(C=f?{display:"inline"}:null,n[0]=f,n[1]=C):C=n[1];var b=C,v=_?c.noop:null,S;n[2]!==v?(S=(e||(e=r("stylex")))(v),n[2]=v,n[3]=S):S=n[3];var R=S;if(i==="div"&&!_&&!f){var L;n[4]===Symbol.for("react.memo_cache_sentinel")?(L="x9f619 xt0psk2 xjb2p0i x1qlqyl8 x15bjb6t",n[4]=L):L=n[4],R=L}var E;i==="randomSpan"?window.customElements?E=y:E="span":E=i;for(var k=h[1],I=0;I<k;I++)g=u.jsx(E,{className:R,style:b,children:g});var T;n[5]!==E||n[6]!==g?(T=u.jsx(E,{children:g}),n[5]=E,n[6]=g,n[7]=T):T=n[7],g=T;for(var D=h[0],x=0;x<D;x++)g=u.jsx(E,{className:R,style:b,children:g});return r("useGHLScrambledLabelMitigationLogger")(l),g}l.default=C}),98);
__d("GamingDestinationFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("6203"),s=o("FalcoLoggerInternal").create("gaming_destination",e),u=s;l.default=u}),98);
__d("GamingVideoDestinationLoggingContext",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u={external_entrypoint:"unknown",surface:"unknown"},c=s.createContext(u);l.default=c}),98);
__d("fbjs/lib/ExecutionEnvironment",["ExecutionEnvironment"],(function(t,n,r,o,a,i){"use strict";var e;a.exports=e||(e=n("ExecutionEnvironment"))}),null);
__d("randomShuffle",["randomInt"],(function(t,n,r,o,a,i,l){function e(e,t,n){if(t===void 0&&(t=0),n===void 0&&(n=0),t>e.length-1-n)return e;for(var o=e.length-1-n;o>t;o--){var a=r("randomInt")(o+1);if(a!==o){var i=e[a];e[a]=e[o],e[o]=i}}return e}l.default=e}),98);
__d("useGamingVideoDestinationEventLogger",["GamingDestinationFalcoEvent","GamingVideoDestinationLoggingContext","react","react-compiler-runtime"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.useCallback,c=s.useContext;function d(){var e=o("react-compiler-runtime").c(10),t=c(r("GamingVideoDestinationLoggingContext")),n;e[0]!==t?(n=function(n,o){r("GamingDestinationFalcoEvent").log(function(){return babelHelpers.extends({event:n},t,o)})},e[0]=t,e[1]=n):n=e[1];var a=n,i;e[2]!==a?(i=function(t){a("click",t)},e[2]=a,e[3]=i):i=e[3];var l=i,s;e[4]!==a?(s=function(t){a("impression",t)},e[4]=a,e[5]=s):s=e[5];var u=s,d;return e[6]!==l||e[7]!==a||e[8]!==u?(d={logClick:l,logEvent:a,logImpression:u},e[6]=l,e[7]=a,e[8]=u,e[9]=d):d=e[9],d}l.default=d}),98);
__d("useShallowEqualMemo",["shallowEqual","useCustomEqualityMemo"],(function(t,n,r,o,a,i,l){"use strict";function e(e){return r("useCustomEqualityMemo")(e,r("shallowEqual"))}l.default=e}),98);